### ISSUE TITLE
죠르디 프로필 구현 - 세민

### ISSUE THREAD

**Issue by linohoch** [2021-SMHRD-IITP-Bigdata-5/Thinking#1]
- [x] 죠르디 얼굴
- [x] 죠르디 몸통
- [x] 죠르디 노트북

**Comment by semin5669** [comment]
- [x] 치즈덕 팝콘
- [x] 치즈덕 머리
- [ ] 치즈덕 얼굴
- [ ] 치즈덕 컬러는 엘로우
- [ ] 치즈덕 컬러는 화이트
